---
title: "Forecasting the old-age dependency ratio to determine a sustainable pension age"
author: Rob J Hyndman$^{1*}$, Yijun Zeng$^2$, Han Lin Shang$^3$
documentclass: anzsauth
classoption: doublespace
bibliography: pensionage.bib
biblio-style: anzsj
toc: false
output:
  bookdown::pdf_document2:
    fig_caption: yes
    citation_package: natbib
    fig_height: 5
    fig_width: 8
    keep_tex: yes
    number_sections: yes
    includes:
      in_header: anzjs_preamble.tex
---

# Summary {-}

We forecast the old-age dependency ratio for Australia under various pension age proposals, and estimate a pension age scheme that will provide a stable old-age dependency ratio at a specified level. Our approach involves a stochastic population forecasting method based on coherent functional data models for mortality, fertility and net migration, which we use to simulate the future age-structure of the population. Our results suggest that the Australian pension age should be increased to 68 by 2030, 69 by 2036, and 70 by 2050, in order to maintain the old-age dependency ratio at 23%, just above the 2018 level. Our general approach can easily be extended to other target levels of the old-aged dependency ratio and to other countries.

**Keywords:** coherent forecasts, demographic components, functional time series, pension age.


```{r child='PensionAge.Rmd'}
```

